# -*- coding: utf-8 -*-
"""A_3(Pandas).ipynb

Automatically generated by Colab.

"""

#1
import pandas as pd

Tid=[1,2,3,4,5,6,7,8,9,10]
Refund=['Yes','No','No','Yes','No','No','Yes','No','No','No']
maritalStatus=['Single','Married','Single','Married','Divorced','Married','Divorced','Single','Married','Single',]
taxableIncome=['125k','100k','70k','120k','95k','60k','220k','85k','75k','90k']
Cheat=["No","No","No","No","Yes","No","No","Yes","No","Yes"]
dic={"Tid":Tid,"Refund":Refund,"Marital Status":maritalStatus,"Taxable Income":taxableIncome,"Cheat":Cheat}
df=pd.DataFrame(dic)
print(df)

#2
import pandas as pd

Tid=[1,2,3,4,5,6,7,8,9,10]
Refund=['Yes','No','No','Yes','No','No','Yes','No','No','No']
maritalStatus=['Single','Married','Single','Married','Divorced','Married','Divorced','Single','Married','Single',]
taxableIncome=['125k','100k','70k','120k','95k','60k','220k','85k','75k','90k']
Cheat=["No","No","No","No","Yes","No","No","Yes","No","Yes"]
dic={"Tid":Tid,"Refund":Refund,"Marital Status":maritalStatus,"Taxable Income":taxableIncome,"Cheat":Cheat}
df=pd.DataFrame(dic)

print(df.loc[[0,4,7,8]])

#3
import pandas as pd

Tid=[1,2,3,4,5,6,7,8,9,10]
Refund=['Yes','No','No','Yes','No','No','Yes','No','No','No']
maritalStatus=['Single','Married','Single','Married','Divorced','Married','Divorced','Single','Married','Single',]
Tax=['125k','100k','70k','120k','95k','60k','220k','85k','75k','90k']
Cheat=["No","No","No","No","Yes","No","No","Yes","No","Yes"]
dic={"Tid":Tid,"Refund":Refund,"Marital Status":maritalStatus,"Taxable Income":Tax,"Cheat":Cheat}
df=pd.DataFrame(dic)

print(df.iloc[3:8])
print()
print(df.iloc[4:9,2:5])
print()
print(df.iloc[:,1:4])

#4
import pandas as pd

df = pd.read_csv("Iris.csv")

print(df.head())

#5
import pandas as pd

df = pd.read_csv("Iris.csv")

df_mod= df.drop(index=3)

df_mod= df_mod.drop(columns=df_mod.columns[2])

print(df_mod)

#6
import pandas as pd

data = {
    "ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Dept": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Sal": [50000, 70000, 65000, 55000, 60000],
    "Experience": [4, 8, 10, 3, 12],
    "Joining": ["2020-03-15", "2017-07-19", "2013-06-01", "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}

df = pd.DataFrame(data)

print("Shape:", df.shape)
print()
print(df.info())
print()
print(df.describe())
print()
print(df.head(5))
print()
print(df.tail(3))
print()
print("Avg Sal:", df["Sal"].mean())
print("Total Bonus:", df["Bonus"].sum())
print("Youngest Age:", df["Age"].min())
print("Max Rating:", df["Rating"].max())
print()
print(df.sort_values(by="Sal", ascending=False))
print()
df["Perf"] = pd.cut(df["Rating"], bins=[0, 4.0, 4.5, 5.0], labels=["Avg", "Good", "Excel"])
print()
print(df.isnull().sum())
print()
df.rename(columns={"ID": "Emp_ID"}, inplace=True)
print(df[(df["Experience"] > 5) & (df["Dept"] == "IT")])
print()
df["Tax"] = df["Sal"] * 0.1
df.to_csv("modified_employees.csv", index=False)

